gin:
  mode: release
  log:
    level: info
    format: json

application:
  name: BiteBattle
  version: 1.0.0
  environment: prod
  jwt_secret: gcp-secret://projects/612596290944/secrets/JWT_SECRET/versions/latest

auth0:
  domain: gcp-secret://projects/612596290944/secrets/AUTH0_DOMAIN/versions/latest
  client_id: gcp-secret://projects/612596290944/secrets/AUTH0_CLIENT_ID/versions/latest
  client_secret: gcp-secret://projects/612596290944/secrets/AUTH0_CLIENT_SECRET/versions/latest
  management_api: gcp-secret://projects/612596290944/secrets/AUTH0_MANAGEMENT_API/versions/latest
  management_token_url: gcp-secret://projects/612596290944/secrets/MANAGEMENT_TOKEN_URL/versions/latest

db:
  host: gcp-secret://projects/612596290944/secrets/DB_HOST/versions/latest
  port: gcp-secret://projects/612596290944/secrets/DB_PORT/versions/latest
  user: gcp-secret://projects/612596290944/secrets/DB_USER/versions/latest
  pass: gcp-secret://projects/612596290944/secrets/DB_PASS/versions/latest
  name: gcp-secret://projects/612596290944/secrets/DB_NAME/versions/latest
  instance_connection_name: gcp-secret://projects/612596290944/secrets/INSTANCE_CONNECTION_NAME/versions/latest

gcs:
  profile_bucket: gcp-secret://projects/612596290944/secrets/GCS_PROFILE_BUCKET/versions/latest
  object_url: https://storage.googleapis.com/

google_places:
  api_key: gcp-secret://projects/612596290944/secrets/GOOGLE_PLACES_API_KEY/versions/latest
  api_endpoint: https://maps.googleapis.com/maps/api/place/textsearch/json

vertex:
  project_id: bitebattle
  location: us-central1
  model: gemini-2.0-flash-001
  auth_token: 