version: '3.8'

services:
  db:
    image: postgres:15
    container_name: bitebattle-db
    restart: always
    environment:
      POSTGRES_DB: bitebattle_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
