name: Deploy to Cloud Run

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches:
      - master

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker for GCR
        run: gcloud auth configure-docker

      - name: Build and push Docker image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/server .
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/server

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy bitebattle-backend \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/server \
            --add-cloudsql-instances=bitebattle:us-central1:bitebattle-db \
            --set-env-vars "INSTANCE_CONNECTION_NAME=bitebattle:us-central1:bitebattle-db" \
            --set-secrets "DB_USER=db-user:latest,DB_PASS=db-pass:latest,DB_NAME=db-name:latest,JWT_SECRET=jwt-secret:latest,GOOGLE_PLACES_API_KEY=google-places-api-key:latest" \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated