name: Deploy to Cloud Run

on:
  push:
    branches: [master]
    paths-ignore:
      - 'README.md'
      - 'Makefile'
      - '.github/**'
      - 'docs/**'
  pull_request:
    branches: [master]
    paths-ignore:
      - 'README.md'
      - 'Makefile'
      - '.github/**'
      - 'docs/**'
  workflow_call:
    secrets:
      GCP_SA_KEY:
        required: true
      INSTANCE_CONNECTION_NAME:
        required: true

env:
  IMAGE: gcr.io/bitebattle/server
  REGION: us-central1
  SERVICE: bitebattle-backend

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for GCR
        run: gcloud auth configure-docker

      - name: Build Docker image
        run: docker build -t $IMAGE .

      - name: Push Docker image
        run: docker push $IMAGE

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy $SERVICE \
            --image $IMAGE \
            --add-cloudsql-instances=${{ secrets.INSTANCE_CONNECTION_NAME }} \
            -- set-env-vars=APP_ENV=prod \
            --platform managed \
            --region $REGION \
            --allow-unauthenticated
